services:
  - type: web
    name: project-rakshak
    runtime: docker
    plan: free # Change to starter ($7/mo) if running heavy 25MB satellite GeoTIFFs
    region: oregon
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
